language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mhamilton/docker-react -f Deockerfile.dev .

script:
  - docker run -e CI=true mhamilton/docker-react npm run test