# docker run -p 3000:3000
# -v /app/node_modules
# -v ~/frontend/app
# mhamilton/frontend

version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'